# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_text',
            field=models.CharField(max_length=555),
        ),
    ]
